2021-12-07 04:21:04 ERROR UserDaoImpl:51 - org.postgresql.util.PSQLException: ERROR: relation "ers_users" does not exist
  Position: 13
2021-12-07 04:21:46 ERROR UserDaoImpl:51 - org.postgresql.util.PSQLException: ERROR: relation "ers_users" does not exist
  Position: 13
2021-12-07 04:26:01 ERROR UserDaoImpl:51 - org.postgresql.util.PSQLException: ERROR: relation "ers_users" does not exist
  Position: 13
2021-12-07 04:26:02 ERROR UserDaoImpl:78 - org.postgresql.util.PSQLException: ERROR: relation "ers_users" does not exist
  Position: 15
2021-12-07 04:28:51 ERROR UserDaoImpl:51 - org.postgresql.util.PSQLException: ERROR: value too long for type character varying(50)
2021-12-07 04:29:19 ERROR UserDaoImpl:51 - org.postgresql.util.PSQLException: ERROR: value too long for type character varying(50)
2021-12-12 19:08:58 ERROR UserDaoImpl:188 - org.postgresql.util.PSQLException: FATAL: password authentication failed for user "kchilds"
2021-12-12 19:11:31 ERROR UserDaoImpl:188 - org.postgresql.util.PSQLException: FATAL: password authentication failed for user "adept"
2021-12-16 19:58:53 ERROR ReimbursementDaoImpl:127 - org.postgresql.util.PSQLException: ERROR: column "ers_user_id" does not exist
  Position: 40
2021-12-16 20:04:15 ERROR ReimbursementDaoImpl:127 - org.postgresql.util.PSQLException: ERROR: column "ers_user_id" does not exist
  Position: 40
2021-12-16 20:05:49 ERROR ReimbursementDaoImpl:127 - org.postgresql.util.PSQLException: ERROR: column "ers_user_id" does not exist
  Position: 40
2021-12-16 20:13:17 ERROR ReimbursementDaoImpl:127 - org.postgresql.util.PSQLException: ERROR: column "ers_author" does not exist
  Position: 40
2021-12-17 04:12:20 ERROR ReimbursementDaoImpl:148 - org.postgresql.util.PSQLException: No results were returned by the query.
2021-12-17 04:12:44 ERROR ReimbursementDaoImpl:148 - org.postgresql.util.PSQLException: No results were returned by the query.
2021-12-18 17:23:41 ERROR UserDaoImpl:78 - org.postgresql.util.PSQLException: The connection attempt failed.
2021-12-18 17:23:41 ERROR UserDaoImpl:78 - org.postgresql.util.PSQLException: The connection attempt failed.
2021-12-18 17:54:33 ERROR UserDaoImpl:78 - org.postgresql.util.PSQLException: The connection attempt failed.
2021-12-18 17:54:33 ERROR UserDaoImpl:78 - org.postgresql.util.PSQLException: The connection attempt failed.
2021-12-18 17:56:31 ERROR UserDaoImpl:188 - org.postgresql.util.PSQLException: The connection attempt failed.
2021-12-18 17:56:36 ERROR UserDaoImpl:188 - org.postgresql.util.PSQLException: The connection attempt failed.
2021-12-18 17:56:51 ERROR UserDaoImpl:188 - org.postgresql.util.PSQLException: The connection attempt failed.
2021-12-18 18:02:43 ERROR UserDaoImpl:78 - org.postgresql.util.PSQLException: The connection attempt failed.
2021-12-18 18:02:43 ERROR UserDaoImpl:78 - org.postgresql.util.PSQLException: The connection attempt failed.
2021-12-18 18:03:37 ERROR UserDaoImpl:78 - org.postgresql.util.PSQLException: The connection attempt failed.
2021-12-18 18:03:37 ERROR UserDaoImpl:78 - org.postgresql.util.PSQLException: The connection attempt failed.
2021-12-18 18:05:54 ERROR UserDaoImpl:78 - org.postgresql.util.PSQLException: The connection attempt failed.
2021-12-18 18:05:54 ERROR UserDaoImpl:78 - org.postgresql.util.PSQLException: The connection attempt failed.
2021-12-20 00:24:02 ERROR UserDaoImpl:78 - org.postgresql.util.PSQLException: The connection attempt failed.
2021-12-20 00:24:02 ERROR UserDaoImpl:78 - org.postgresql.util.PSQLException: The connection attempt failed.
2021-12-20 00:24:02 ERROR UserDaoImpl:78 - org.postgresql.util.PSQLException: The connection attempt failed.
2021-12-20 00:24:02 ERROR UserDaoImpl:78 - org.postgresql.util.PSQLException: The connection attempt failed.
2021-12-20 00:24:02 ERROR UserDaoImpl:78 - org.postgresql.util.PSQLException: The connection attempt failed.
2021-12-20 00:24:02 ERROR UserDaoImpl:78 - org.postgresql.util.PSQLException: The connection attempt failed.
2021-12-20 00:26:00 ERROR UserDaoImpl:78 - org.postgresql.util.PSQLException: The connection attempt failed.
2021-12-20 00:26:00 ERROR UserDaoImpl:78 - org.postgresql.util.PSQLException: The connection attempt failed.
2021-12-20 00:26:00 ERROR UserDaoImpl:78 - org.postgresql.util.PSQLException: The connection attempt failed.
2021-12-20 00:26:00 ERROR UserDaoImpl:78 - org.postgresql.util.PSQLException: The connection attempt failed.
2021-12-20 00:26:00 ERROR UserDaoImpl:78 - org.postgresql.util.PSQLException: The connection attempt failed.
2021-12-20 00:26:00 ERROR UserDaoImpl:78 - org.postgresql.util.PSQLException: The connection attempt failed.
2021-12-20 00:32:36 ERROR UserDaoImpl:78 - org.postgresql.util.PSQLException: The connection attempt failed.
2021-12-20 00:33:08 ERROR UserDaoImpl:78 - org.postgresql.util.PSQLException: The connection attempt failed.
2021-12-20 00:41:31 ERROR UserDaoImpl:78 - org.postgresql.util.PSQLException: The connection attempt failed.
2021-12-20 00:58:10 ERROR UserDaoImpl:78 - org.postgresql.util.PSQLException: The connection attempt failed.
2021-12-20 00:58:43 ERROR UserDaoImpl:78 - org.postgresql.util.PSQLException: The connection attempt failed.
2021-12-20 01:01:46 ERROR UserDaoImpl:78 - org.postgresql.util.PSQLException: The connection attempt failed.
2021-12-20 01:08:47 ERROR UserDaoImpl:78 - org.postgresql.util.PSQLException: The connection attempt failed.
2021-12-20 01:11:24 ERROR UserDaoImpl:78 - org.postgresql.util.PSQLException: The connection attempt failed.
